### ISSUE TITLE
Error when trying to dockerize

### ISSUE THREAD

**Issue by khusseini** [larsks/dockerize#5]
Hi there,

when I run dockerize I get the following:

```
$ dockerize dockerize -t php /Users/me/source/local/php-lxc/build/php-5.6.18/usr/local/php/bin
Traceback (most recent call last):
  File "/usr/local/bin/dockerize", line 9, in <module>
    load_entry_point('dockerize==0.2', 'console_scripts', 'dockerize')()
  File "build/bdist.macosx-10.11-x86_64/egg/dockerize/main.py", line 117, in main
  File "build/bdist.macosx-10.11-x86_64/egg/dockerize/dockerize.py", line 89, in add_file
ValueError: dockerize: container paths must be fully qualified
```

**Comment by larsks** [comment]
It looks like you're trying to run `dockerize` on OS X.  The tool will only work under Linux.  I'll add a note to the README to make that clear.

**Comment by khusseini** [comment]
Oh my bad. Am new to OSx and didn't think of that xD
